[tools]
# Package managers
uv = "0.9.18"

# Development tools
pre-commit = "4.5.1"

# Aqua Tools
"aqua:gitleaks/gitleaks"      = "8.30.0"
"aqua:rhysd/actionlint"       = "1.7.9"
"aqua:suzuki-shunsuke/pinact" = "3.7.2"
"aqua:zizmorcore/zizmor"      = "1.19.0"

# GitHub Tools
"github:rvben/rumdl" = "0.0.204"
