[tools]
# Package managers
uv = "0.9.17"

# Development tools
pre-commit = "4.5.0"

# Aqua Tools
"aqua:gitleaks/gitleaks"      = "8.30.0"
"aqua:rhysd/actionlint"       = "1.7.9"
"aqua:suzuki-shunsuke/pinact" = "3.5.0"
"aqua:zizmorcore/zizmor"      = "1.18.0"

# Cargo Tools
"cargo:rumdl" = "0.0.194"
